const data = {
scrollData: [
    {id: 1,
        src: '../../zusammen_web.jpg',
        alt: 'scroll1',
    },
    {id: 2,
        src: '../../rolle_lang_zusammen_web.jpg',
        alt: 'scroll2',
    },
    {id: 3,
        src: '../../Nachtflucht_scroll.jpg',
        alt: 'scroll3',
    },
    {id: 4,
        src: '../../Paski_scroll.jpg',
        alt: 'scroll3',
    },
    {id: 6,
        src: '../../labyrinth_scroll.jpg',
        alt: 'scroll3',
    },
    {id: 7,
        src: '../../Kosmos_scroll.jpg',
        alt: 'scroll3',
    },
], paintingData: [
    {id: 1,
        src: '../../walteryu1.png',
        alt: 'scroll1',
    },
    {id: 2,
        src: '../../walteryu2.png',
        alt: 'scroll2',
    },
    {id: 3,
        src: '../../walteryu4.png',
        alt: 'scroll3',
    },
    {id: 4,
        src: '../../walteryu3.png',
        alt: 'scroll3',
    },
    {id: 6,
        src: '../../baby_yu.JPG',
        alt: 'scroll3',
    },
]
};

export default data;